#!/usr/bin/env sh

#daemon_active=$(ls /run/user/1000/emacs >/dev/null 2>&1 | wc -l)

files="$@"

emacs_active=$(systemctl status --user emacs.service | \
		   grep Active: | \
		   awk '{print $2}')


# gui emacs
## -c starts always in new window because it is gui
## </dev/null no output in current terminal window
## &>/dev/null start in new detached terminal window
emacsclient -c "$files" &> /dev/null &
#emacsclient -c "$files" </dev/null &>/dev/null &
## start in same terminal window
# TODO emacsclient "$files" </dev/null &>/dev/null &

#emacsclient -c -a -t -- "$files" </dev/null &>/dev/null &
#emacsclient -c --alternate-editor='' -- "$files" </dev/null &>/dev/null &

# tui emacs
#emacsclient -t "$@"
