#!/bin/bash

# usage: base_conversion integer ibase obase
# with 2<=ibase<=36 (26+10)
# with 2<=obase<=36 (26+10)

echo "obase=$3; ibase=$2; \
	$( printf $1 | \
	## bc needs capitals
	tr a-z A-Z )" | \
	bc | \
	## remove eol
	sed ':a;N;$!ba;s/\n//g' | \
	sed 's/\\//g'
