#!/usr/bin/env bash

src="$XDG_DATA_HOME/c/"
dst="$XDG_DATA_HOME/b"

sudo chattr -R -i $dst >/dev/null 2>&1

rsync -aAXv --delete --links --log-file=$XDG_LOGS_HOME/buc2b/$(date +%s) $src $dst | tee -a $XDG_LOGS_HOME/buc2b/$(date +%s)

sudo chattr -R +i $dst >/dev/null 2>&1

cd - &> /dev/null
