#!/usr/bin/env bash


# backup DATA_HOME/c, CONFIG_HOME and history


# usage:
## % c2b [rsync-options]


# example:
## % c2b --dry-run
## % c2b --delete --links


options=$@
timestamp="$(date +%s)"
log_file="$XDG_LOGS_HOME/c2b/$timestamp"


## copy $src1
##
## $XDG_DATA_HOME/c ($HOME/.local/share/c)
src1="$XDG_DATA_HOME/c/"
##
## and $src2
##
## $XDG_CONFIG_HOME ($HOME/.config)
src2="$XDG_CONFIG_HOME"
##
## and $src3
##
## $XDG_CONFIG_HOME ($HOME/.logs/history/history)
src3="$XDG_LOGS_HOME/history"
##
## to $dst the dynamic data backup
##
## $XDG_DATA_HOME/b ($HOME/.local/share/b)
dst="$XDG_DATA_HOME/b"


# ## make dynamic data backup writable
sudo chattr -R -i $dst >/dev/null 2>&1


# copy c to b
# and create logging
rsync -aAXv --log-file=$logfile $options $src1 $dst | tee -a $logfile


# copy .config to b
# and create logging
rsync -aAXv --log-file=$logfile $options $src2 $dst | tee -a $logfile


# copy history to b
# and create logging
rsync -aAXv --log-file=$logfile $options $src3 $dst | tee -a $logfile


# ## protect dynamic data backup against writing
sudo chattr -R +i $dst >/dev/null 2>&1
