#! /usr/bin/env sh

###
###            _
###   ___ __ _| | ___     ___ _   _ _ __ ___  ___
###  / __/ _` | |/ __|   / __| | | | '_ ` _ \/ __|
### | (_| (_| | | (__    \__ \ |_| | | | | | \__ \
###  \___\__,_|_|\___|___|___/\__,_|_| |_| |_|___/
###                 |_____|

###  # # # # # #
###       #
###  # # # # # #
###

: '
calc_sums
calculate file checksums
copyright (c) 2022  |  oxo

GNU GPLv3 GENERAL PUBLIC LICENSE
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
https://www.gnu.org/licenses/gpl-3.0.txt

@oxo@qoto.org


# usage

calc_sums [hash] [directory]

example:
calc_sums sha3-512 /home/oxo

# '


hash=$1 ## md5 rmd160 sha1 sha256 sha512 sha3-512
input_dir=$2

# calculate checksums
#hash="sha3-512"  ## md5 rmd160 sha1 sha256 sha512 sha3-512
printf "writing $hash checksums...\n"
files=$(find "$input_dir" -maxdepth 1 -type f)

for file in $files; do
	openssl dgst -$hash $file >> "$hash"_checksums.txt
done
