#! /usr/bin/env sh

#set -o errexit
#set -o nounset
set -o pipefail

arg=$1

source $XDG_DATA_HOME/c/git/code/source/function/text_appearance

if [[ -z $arg ]]; then

    sha3-512sum -c $PWD/sha3-512sums
    exit 0

fi

file_name=$(realpath $arg)


# calculate ist of file_name

ist_sum=$(sha3-512sum "$file_name" | cut -d ' ' -f 1)


# define hashlist (sha3-512sums)

hash_list=$(dirname $file_name)/sha3-512sums

if [[ -f $hash_list ]]; then

    ## search ist of file_name in hashlist and grep the matching soll script_name
    soll_name=$(grep $ist_sum $hash_list | awk '{print $2}')

else

    printf "${fg_amber}%s${st_def} does not exist\n" "$hash_list"
    exit 88

fi


# verify checksum

printf "$(BGx 222222)%s${st_def}\r" "$file_name"
sleep 0.5
if [[ "$file_name" != "$soll_name" ]]; then

    ## exit if file_name does not match soll_name
    printf "$(BGx 222222)${fg_amber}%s${st_def} checksum FAILED" "$file_name"
    sleep 1
    echo
    exit 88

else

    printf "$(BGx 222222)${fg_green}%s${st_def} checksum OK\r" "$file_name"
    sleep 1
    tput el
    exit 0

fi
