#! /usr/bin/env sh

## usage:	chln [non-default target directory]

: '
change symlinks $HOME to current $USER
old: /home/user01/dir/symlink
new: /home/user02/dir/symlink

default applies on $HOME/.config/shln
when it is moved to another $USER
# '

## non-default target
target="$1"


# designate target

if [[ -z "$target" ]]; then

    ## default target
    target="$XDG_CONFIG_HOME/shln"

else

    ## non-default target
    :

fi


# execute chln

for symlink in $(find $target -type l); do

    ## only for links to old users $HOME
    if [[ "$(realpath $symlink)" == "/home/*" ]]; then

	## -f canonicalize every symlink
	new_target=$( \
		      readlink -f $symlink | \
			  cut -d / -f 4- | \
			  awk -v new_home="$HOME/" '{print new_home $0}' \
		  )

	ln -sf $new_target $symlink

    fi

done
