#! /usr/bin/env sh

## usage:	chln $target_directory

: '
change symlinks target to current $USER home
i.e.
old: readlink old symlink is /home/old-user/dir/symlink
new: readlink new symlink is /home/new-user/dir/symlink

script applies to targets inside $HOME
# '

## read target_directory
target_dir="$1"


# designate target

if [[ ! -d "$target_dir" ]]; then

    printf 'target directory not found\n'
    exit 23

fi


for xlink in $(find "$target_dir" -xtype l -print); do
    ## xlink is a broken symlink inside target_dir

    target=$(readlink "$xlink")
    #target=$(readlink -f "$xlink")
    link_name=$(realpath --strip "$xlink")

    if [[ "$target" == /home/* && \
	      "$link_name" == /home/* ]]; then
	## both target and link_name start with /home/

	## /home/old_user is replaced by /home/$USER in target filepath
	new_target=$(cut -d / -f 4- | <<< "$target" \
			 | awk -v new_home="$HOME/" '{print new_home $0}' \
		  )

	## /home/old_user is replaced by /home/$USER in link_name filepath
	new_link_name=$(cut -d / -f 4- | <<< "$link_name" \
			    | awk -v new_home="$HOME/" '{print new_home $0}' \
		     )

	if [[ -f "$new_target" ]]; then
	    ## new_target exist

	    ## overwrite symbolic link link_name
 	    ln --symbolic --force "$new_target" "$new_link_name"
	    printf "DEV$LINENO %s %s\n" "$new_target" "$new_link_name"

	fi

    fi

done
