#!/usr/bin/env bash
set -o errexit
#set -o nounset
set -o pipefail

# set useragent from an online updated list

# usage
# chua [--manual]

# dependencies
# https://www.useragents.me/api


# getargs
arg1=$1
qb_conf="$XDG_CONFIG_HOME/qutebrowser/config.py"


# sourcing
source $XDG_DATA_HOME/c/git/code/source/function/text_appearance
source_html='https://www.useragents.me/#most-common-desktop-useragents-json-csv'
source_www='https://www.useragents.me/api'
# same source?
#https://techblog.willshouse.com/2012/01/03/most-common-user-agents/


# set ua current logging
lnuac="$XDG_LOGS_HOME/network/user_agent/current"


# set timestamp
timestamp=$(date +%Y%m%d_%H%M%S)


# set html file location
html_file="$XDG_CACHE_HOME/temp/${timestamp}_chua.html"


# get api data
# #api_data=$(curl $source_www)
curl $source_html > $html_file

# process api data
if [[ "$arg1" == '--manual' ]]; then

    printf '\ncurrent USER_AGENT:\n   %s\n' "$(head -n 1 $lnuac)"
    ua_sel=$(printf '%s' $api_data | jq '.data[] | .ua' | fzf --height=~20)

else

    # #ua_sel=$(printf '%s' $api_data | jq '.data[0] | .ua')
    ua_sel_html=$(grep -A 1 'most common desktop useragents list conveniently in TSV' $html_file | tail -n 1 | cut -d '>' -f 2 | awk 'NF{NF-=1};1')

fi

ua=$(printf '%s' $ua_sel | sed -e 's/^"//' -e 's/"$//')

[[ -z $ua ]] && ua=$ua_sel_html


# prepend timestamp and selected ua to ua log file (lnuac)
sed -i "1i $timestamp" $lnuac
sed -i "1i $ua" $lnuac


# change qutebrowser settings
qb_line_2_change=$(grep ^c.content.headers.user_agent $qb_conf)
qb_string_2_change=$(printf "$qb_line_2_change" | awk -F "'" '{print $2}')
sed -i "s|$qb_string_2_change|$ua|" $qb_conf


# envirnment variable is changed via .zshenv (restart zsh)
## only info here if ua is changed:
if [[ "$USER_AGENT" != "$ua" ]]; then

    printf "new USER_AGENT:\n   ${BLUE}%s${NOC}\n" "$ua"

fi
