#!/bin/bash

#set -o history -o histexpand

lst_cmd="$(fc -R -ln -1)"
#lsmd=$(fc -ln -1)
last_cmd=$(sed 's/^[[:space:]]*//' <<< "$lst_cmd")

#printf "$(fc -ln -1)\n"
#printf "$last_cmd\n"

printf "x: $lst_cmd\n"
printf "y: $last_cmd\n"
grep -c $last_cmd "$HISTFILE"
printf "instances\n"
printf "remove from history? (y/N)"

#sed -i '/$last_cmd/d' $HISTFILE

