#!/usr/bin/env bash

# organize directory items

# TODO daily/weekly

# usage:
## date_dir [$directory]

## execute in $PWD, unless ...
dir=$PWD
if [[ -n $1 ]]; then

    if [[ -d $1 ]]; then

	## a directory is given
	dir=$1

    fi

fi

# monthly
## organize directory items into monthly folders
for item in $(ls $dir); do

    year_month=$(stat -c %Y $item | xargs -I {} date -d @{} +'%Y%m')

    dir_y=$(printf "$year_month" | head -c 4)
    dir_m=$(printf "$year_month" | tail -c 2)

    [[ -d "$dir_y/$dir_m" ]] || mkdir -p "$dir_y/$dir_m"

    mv $item "$dir_y/$dir_m"

done
