#!/bin/bash
#
##
###      _          _
###   __| | ___  __| |_   _ _ __
###  / _` |/ _ \/ _` | | | | '_ \
### | (_| |  __/ (_| | |_| | |_) |
###  \__,_|\___|\__,_|\__,_| .__/
###                        |_|
###  _ _|_ _ ._    _  _
### (_\/|_(_)|_)\/(_|(/_
###   /      |  /  _|
###
### dedup (c) 2020 - 2021 cytopyge
###
### remove duplicate lines from file, while preserving line order
###
### usage: dedup <source_file> [destination_file]
##
#


src_file=$1
dst_file=$2


dedup()
{
	## cat -n --> print file with added linenumbers (used for sorting)
	cat -n $src_file | \

		## sort -u -k 2 --> output uniq rows based on colomn 2 to EOL
		sort -u -k 2 | \

		## sort -n k 1,1 --> output numerical based on column 1
		sort -n -k 1,1 | \

		## remove linenumbers from file, by showing only second column
		cut -f 2
}


#if [[ -z $dst_file ]]; then

	dedup

#else

#	dedup > $dst_file

#fi
