#! /usr/bin/env sh

# cool clock with figlet fonts chosen via fzf

font="$(command ls $XDG_CONFIG_HOME/figlet | fzf)"

trap "tput cnorm; return 1" SIGINT

erase()
{
    tput el1
    tput rc
    tput ed
}


tput civis
tput sc


while true; do

    echo
    figlet -d $XDG_CONFIG_HOME/figlet -f $font $(date +'%H:%M:%S')
    sleep 1
    erase

    echo
    figlet -d $XDG_CONFIG_HOME/figlet -f $font $(date +'%H.%M.%S')
    sleep 1
    erase

done
