#! /usr/bin/env sh

# fzf unique words from input string
# each word on it's own line
# primarily designed to be used in conjuction with yank_buffer
# i.e.: yank_buffer | fzf_word


receive()
{
    ## from clipboard
    std_in="$(wl-paste)"
    #wl-paste < "$std_in"
}


process()
{
    # remove double spaces
    # create word list with only single instances
    ## tr: replace spaces with eol
    clean_uniq_word_list=$(tr ' ' '\n' <<< "$std_in" | sort | uniq)
}


send()
{
    ## to fzf

    ### as multiline
    #string_select=$(printf '%s' "$clean_uniq_word_list" | fzf -m)

    ### as single line
    string_select=$(printf '%s' "$clean_uniq_word_list" | fzf -m | tr '\n' ' ')

}


copy_clipboard()
{
    printf '%s' "$string_select" | wl-copy
}


main()
{
    sleep 1
    receive
    process
    send
    copy_clipboard
}

main
