#! /usr/bin/env sh

# usage: gpg-pass-vfy $keyid

#set -o errexit
#set -o nounset
set -o pipefail


args="$@"
get_args ()
{
    keyid="$1"
}


process_args ()
{
    if [[ -z "$keyid" ]]; then

	keyid=$(gpg --list-keys --with-colons \
		    | rg --no-line-number pub \
		    | awk -F ':' '{print $5}' \
		    | fzf
	     )

    fi
}


get_pass ()
{
    gpg-connect-agent reloadagent /bye

    echo 'signme' \
	| gpg \
	      --yes \
	      --batch \
	      --passphrase-fd 1 \
	      --local-user "$keyid" \
	      --armor \
	      --sign \
	      - \
	      > /dev/null 2>&1
}


main ()
{
    get_args $args
    process_args
    get_pass
}

main
