#! /usr/bin/env sh

file="$HOME"/.cache/test/historytest

delimiter=':0;'
line_sel=$(awk -F "$delimiter" '{print $2}' $file | fzf)

printf '%s\n' "$line_sel"
input=$(printf 'qxct\nline\npart' | fzf --prompt 'delete ')
#TODO DEV fzf -m

case "$input" in

    line )
	## remove all whole lines from file
	sed -i "/^.*${delimiter}${line_sel}$/d" $file
	;;

    part )
	## split line into parts
	line_parts_arr=($line_sel)
	part_sel=$(printf '%s\n' "${line_parts_arr[@]}" | fzf)

	## remove all lines containing selected space delimited part from file
	sed -i "/${part_sel}/d" $file
	;;

    qxct | '' | * )
	exit 0
	;;

esac
