#! /usr/bin/env sh

## history file
histfile="$HOME"/.logs/history/history


show_lines ()
{
    ## show unique history lines
    delimiter=':0;'
    uniq_lines=$(awk -F "$delimiter" '{print $2}' "$histfile" \
		     | nl --number-format ln \
		     | sort --key 2 \
		     | awk '!seen[$2]++ {print}' \
		     | sort --numeric-sort --key 1,1 \
		     | awk '!($1="")' \
		     | sed 's/^[ \t]*//' \
	      )

    line_sel=$(fzf --multi --tac <<< "$uniq_lines")
    # line_sel=$(awk -F "$delimiter" '{print $2}' "$file" | fzf --multi --tac)
}


select_lines ()
{
    printf '%s\n' "$line_sel"
    input=$(printf 'qxct\nline\npart' | fzf --prompt 'delete ')
}


select_action ()
{
    case "$input" in

	line )
	    ## remove all selected lines from file
	    while read line; do

		sed -i "/^.*${delimiter}${line}$/d" "$histfile"

	    done <<< "$line_sel"
	    ;;

	part )
	    split_line
	    select_part

	    case "$part_sel" in

		alt_delim )
		    ## alternative delimiter
		    printf '%s ' 'delimiter:'
		    read -r -n 1 delimiter

		    ## set delimiter
		    [[ -n "$delimiter" ]] && IFS="$delimiter"

		    split_line
		    select_part
		    ;;

	    esac

	    ## remove all lines containing selected space delimited part from file
	    sed -i "/${part_sel}/d" "$histfile"
	    ;;

	qxct | '' | * )
	    exit 0
	    ;;

    esac
}


split_line ()
{
    ## split line into parts
    line_parts_arr=($line_sel)

    ## put parts into array
    line_parts_arr+=(alt_delim)

    IFS=
}


select_part ()
{
    part_sel=$(printf '%s\n' "${line_parts_arr[@]}" | fzf)
}


main ()
{
    show_lines
    select_lines
    select_action
}

main
