#!/bin/bash

kill_proc() {

	local pid

	pid=$(ps -ef | grep -v ^root | fzf -m --cycle --header-lines=1 | awk '{print $2}')

	if [ "x$pid" != "x" ]; then

		echo $pid | xargs kill -${1:-9}

	fi

}


kill_proc
