#!/bin/bash

proc_kill() {

	local pid

	pid=$(ps -ef | grep -v ^root | fzf -m --cycle --header-lines=1 | awk '{print $2}')

	if [ "x$pid" != "x" ]; then

		echo $pid | xargs kill -${1:-9}

	fi

}


proc_kill
