#!/bin/bash


source $HOME/_git/code/sources/functions/reply_functions
source $HOME/_git/code/sources/functions/text_appearance


cursor_up_one_line() {

	tput cuu1

}

kill_proc() {

	local pid

	pid=$(ps -ef | grep -v ^root | fzf -m --cycle --header-lines=1 | awk '{print $2}')

	echo

	if [ "x$pid" != "x" ]; then

		while IFS= read -r line_in_pid;	do

			printf "$(ps -p $line_in_pid -o comm=)\n"

		done <<< "$pid"

		echo
		printf "${YELLOW}kill process(es)? (y/N):${NOC} "

		reply_single

		if printf "$reply" | grep -iq "^y"; then

			printf "\nkilling in progress... "
			echo $pid | xargs kill -${1:-9}
			echo
			printf "${GREEN}complete${NOC}\n"

		else

			printf "\n${RED}aborted by user${NOC}\n"
			printf "no processes were killed\n"
			printf "exiting\n"
			exit

		fi

	fi

}


kill_proc
