#!/usr/bin/env bash
#
##
###
### make_recov
### make offline repo and recovery code
### 2020 - 2022  |  cytopyge
###
### usage:
### make_recov <destination> [rsync_options]
###
### # examples
###
### ## backup
### syncr /home/cytopyge/dock/transfer/tux/home/cytopyge \
###	    --dry-run --links --delete
###
### ## archive
### syncr /home/cytopyge/dock/transfer/tux/home/cytopyge \
###	    --dry-run --links
##
#

## initialize
args="$@"
repo_mount="$HOME/dock/2/aur"
code_mount="$HOME/dock/3/code"

## sourcing
source_dir="$XDG_DATA_HOME/c/git/code/source/function"
source $source_dir/get_sudo
source $source_dir/reply_functions
source $source_dir/text_appearance

make_offl_repo="$XDG_DATA_HOME/c/git/code/tool/make_offl_repo"

## destination
#dest=$1; shift
#[[ ! -d $dest ]] && printf "${MAGENTA}destination not found${NOC}\n" && exit 3

## added rsync options
options="$*"

## rsync options
# -a		is equivalent to -rlptgoD
# --dirs	will create directories specified in the list on the destination
# --links	prevent rsync error: 'skipping non-regular file'


recovery()
{
    repo
    code
}


repo()
{
	# synchronize offline repo		(repo)

	[[ -d $repo_mount ]] && repo_mounted=1

	case $repo_mounted in

		1)
			printf "\n${BLUE}%s${NOC}" "updating offline recovery repo ... "

			sh $make_offl_repo >/dev/null 2>&1

			printf "${BLUE}%s${NOC}\n" "complete"

			printf "\n${BLUE}%s${NOC}\n" "synching offline recovery repo"

			local src="$repo_mount"
			local dst="$dest/repo/"

			[[ -d $dst ]] || mkdir -p $dst

			rsync -aAXv \
				--info=ALL \
				$options \
				$src $dst
			;;

		*)
			printf "\n${YELLOW}no offline repo found${NOC}\n"
			;;

	esac
}


code()
{
    # synchronize offline code		(code)

    ## source list
    source_list=( \
        $XDG_CONFIG_HOME \
        $XDG_DATA_HOME/c/git/code \
        $XDG_DATA_HOME/c/keys \
        $XDG_DATA_HOME/c/git/note \
        $XDG_DATA_HOME/c/git/prvt \
        $HOME/.password-store \
        )

    [[ -d $code_mount ]] && code_mounted=1

    case $code_mounted in

    	1)
	    printf "\n${BLUE}%s${NOC}\n" "synching offline recovery code"

	    local src="$code_mount"
	    local dst="$dest/code/"

	    [[ -d $dst ]] || mkdir -p $dst

	    rsync -aAXv \
    		--info=ALL \
    		$options \
    		$src $dst
	   ;;

    	*)
	   printf "\n${YELLOW}error; no offline repo found${NOC}\n"
	   ;;

    esac
}



