#!/usr/bin/env bash

# connect or disconnect to a network using nmcli

set -e
sudo -v
sudo systemctl start NetworkManager.service

get_nm_info()
{
    echo
    nmcli general
    echo
    nmcli device
    echo
    nmcli connection
    echo
}

## get info before
nm_info_before=$(get_nm_info)

## select device
device_fzf_height=$(nmcli device | wc -l)
device_sel=$(nmcli -t device | fzf --height=$device_fzf_height | awk -F : '{print $1}')
device_type=$(nmcli -t device | grep "$device_sel" | awk -F : '{print $2}')

[[ -z $device_sel ]] && exit 12

## select connection
connection_fzf_height=$(nmcli device | wc -l)
connection_sel=$(nmcli -t connection | grep "$device_type" | fzf --height=$connection_fzf_height | awk -F : '{print $1}')
connection_device=$(nmcli -t connection | grep "$connection_sel" | awk -F : '{print $4}')

[[ -z $connection_sel ]] && exit 13


## set up or down
case $connection_device in

    "")
	nmcli connection up "$connection_sel"
	;;

    *)
	nmcli connection down "$connection_sel"
	;;

esac

## get info after
nm_info_after=$(get_nm_info)

## show info diff
diff <(echo "$nm_info_before") <(echo "$nm_info_after") | grep -e $device_sel -e $connection_sel
