#! /usr/bin/env sh

# requirements: open password-store
# i.e. with: passr open

# usage: passexp $filename
# recommended: yyyymmdd_hhmmss_pass_data

exp_file=$1
vlt_pass="$HOME/.password-store"

mountpoint -q $vlt_pass
[[ $? != 0 ]] && printf "open vault pass and mount to password-store\n"
# vault open $XDG_DATA_HOME/media/vault/pass ~/dock/vlt/pass

# find all gpg files
gpg_files=$(find $vlt_pass/ -type f -name '*.gpg' | sort)

for file in $gpg_files; do

	pass_file=$(printf $file | sed "s|$vlt_pass/||" | sed 's|.gpg$||')

	printf '%s\n' "$file" >> $exp_file
	printf '%s\n' "-------------------------------------------------------------------------------" >> $exp_file
	pass show $pass_file >> $exp_file
	printf '%s\n\n' "===============================================================================" >> $exp_file

done
