#!/usr/bin/env bash

# compile source code from aur packages
# for hajime/4apps.sh#aur_install

src_aur="$HOME/dock/3/source/aur"
#src_aur="$HOME/dock/3/source/aur"
aur_pkgs=($(yay -d $(yay -Qqm)))

for package in "${aur_pkgs[@]}"; do

	cd $package
	makepkg -s

done
