#!/bin/sh

trash="$XDG_CACHE_HOME/trash"
[[ -d $trash ]] || mkdir -p $trash

items="$@"

# if rm options are given in $1
# (i.e. -rf); then skip these
# and just move items to trash

if [[ "$(printf -- "$items" | head -c 1)" == "-" ]]; then

	items="$(echo $items | awk '!($1="")')"

fi

# mv items to trash
mv $items $trash
