#!/bin/bash
#
##
###  _               _           _     _            _    _ _     _
### | |__   ___  ___| |_ ___    | |__ | | __ _  ___| | _| (_)___| |_
### | '_ \ / _ \/ __| __/ __|   | '_ \| |/ _` |/ __| |/ / | / __| __|
### | | | | (_) \__ \ |_\__ \   | |_) | | (_| | (__|   <| | \__ \ |_
### |_| |_|\___/|___/\__|___/___|_.__/|_|\__,_|\___|_|\_\_|_|___/\__|
###                        |_____|
### (c) 2020 cytopyge
###
### update_hosts_blacklist
### update dns hosts file forbidden entries
### thanks to steven black
###
##
#

source ~/_git/code/sources/functions/text_appearance
timestamp=`date "+%Y%m%d_%H%M%S"`

[[ ! -d $HOME/.config/hosts ]] && \
	cd $HOME/.config && \
	git clone https://github.com/StevenBlack/hosts

cd $HOME/.config/hosts
git checkout blacklist
cp hosts archive/$timestamp_archived_hosts
curl https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts > ~/.config/hosts/hosts
git add $HOME/.config/hosts/hosts
git commit -a -m "updated with script $timestamp"
sudo ln -sf ~/.config/hosts/hosts /etc/hosts
printf "${GREEN}update dns hosts blacklist succesfull${NOC}\n"
[[ -f $HOME/_git/private/code/tools/custom_blacklist ]] && \
	sh $HOME/_git/private/code/tools/custom_blacklist && \
	printf "blacklist customized\n"
exit 0
