#!/bin/bash
#
##
###  _               _           _     _            _    _ _     _
### | |__   ___  ___| |_ ___    | |__ | | ___   ___| | _| (_)___| |_
### | '_ \ / _ \/ __| __/ __|   | '_ \| |/ _ \ / __| |/ / | / __| __|
### | | | | (_) \__ \ |_\__ \   | |_) | | (_) | (__|   <| | \__ \ |_
### |_| |_|\___/|___/\__|___/___|_.__/|_|\___/ \___|_|\_\_|_|___/\__|
###                        |_____|
###  _    _
### (_)><(_)
###
### hosts_blocklist
### update dns hosts_blocklist
### copyright (c) 2019 - 2022  |  oxo
###
### GNU GPLv3 GENERAL PUBLIC LICENSE
### This program is free software: you can redistribute it and/or modify
### it under the terms of the GNU General Public License as published by
### the Free Software Foundation, either version 3 of the License, or
### (at your option) any later version.
###
### This program is distributed in the hope that it will be useful,
### but WITHOUT ANY WARRANTY; without even the implied warranty of
### MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
### GNU General Public License for more details.
###
### You should have received a copy of the GNU General Public License
### along with this program.  If not, see <https://www.gnu.org/licenses/>.
### https://www.gnu.org/licenses/gpl-3.0.txt
###
### @oxo@qoto.org
###
##
#

## dependencies
#	https://github.com/StevenBlack/hosts
#	thanks steven black

## usage
#	cd $XDG_CONFIG_HOME/hosts && git checkout blocklist_off
#	cd $XDG_CONFIG_HOME/hosts && git checkout blocklist_on


## example
#	none


# initial definitions

## script
script_name='update_dns_hosts_blocklist'
developer='oxo'
license='gplv3'
initial_release='2019'

## hardcoded variables
source_dir="$XDG_DATA_HOME/c/git/code/source/function"
loc_blocklist="$XDG_CONFIG_HOME/hosts"
source $source_dir/text_appearance

#--------------------------------


create_git_repo()
{
	mkdir -p $loc_blocklist
	cd $loc_blocklist
	touch remove_me
	git init
	git add .
	git commit -m "$(date +%Y%m%d_%H%M%S)_initial_commit_blocklist"
	rm remove_me

	## create branch blocklist_off
	git branch blocklist_off

	## copy original etc/hosts to branch blocklist_off
	git checkout blocklist_off
	[[ -f /etc/hosts ]] && sudo cp /etc/hosts .
	chown $USER:$GROUP hosts
	git add .
	git commit -m "$(date +%Y%m%d_%H%M%S)_created branch blocklist_off"

	## create branch blocklist_on
	git branch blocklist_on
	git checkout blocklist_on
	git add .
	git commit -m "$(date +%Y%m%d_%H%M%S)_created branch blocklist_on"

	## go back to where we came from
	cd -
}


download_blocklist()
{
	## ... copy THE blocklist into branch blocklist_on
	cd $loc_blocklist
	git checkout -f blocklist_on

	#[TODO] define tracking info for branch
	#[TODO] git pull
	curl -O http://sbc.io/hosts/alternates/fakenews-gambling-porn-social/hosts

	git add .
	git commit -a -m "$(date +%Y%m%d_%H%M%S)_blocklist_updated"

	## symlink /etc/hosts to blocklist
	sudo ln -sf $XDG_CONFIG_HOME/hosts/hosts /etc/hosts

	printf "${BLUE}update dns hosts blocklist succesfull${NOC}\n"

	## go back to where we came from
	cd - >/dev/null

	exit 0
}


main()
{
	[[ ! -d $loc_blocklist ]] && create_git_repo
	download_blocklist
}

main
