#!/bin/bash
#
##
###  _               _           _     _            _    _ _     _
### | |__   ___  ___| |_ ___    | |__ | | __ _  ___| | _| (_)___| |_
### | '_ \ / _ \/ __| __/ __|   | '_ \| |/ _` |/ __| |/ / | / __| __|
### | | | | (_) \__ \ |_\__ \   | |_) | | (_| | (__|   <| | \__ \ |_
### |_| |_|\___/|___/\__|___/___|_.__/|_|\__,_|\___|_|\_\_|_|___/\__|
###                        |_____|
### (c) 2019 - 2021 cytopyge
###
### update_hosts_blocklist
### update dns hosts file forbidden entries
### https://github.com/StevenBlack/hosts
### thanks steven black
###
##
#


## usage: cd $XDG_CONFIG_HOME/hosts && git checkout blocklist_off
## usage: cd $XDG_CONFIG_HOME/hosts && git checkout blocklist_on


source $XDG_DATA_HOME/git/code/sources/functions/text_appearance
loc_blocklist="$XDG_CONFIG_HOME/hosts"


create_git_repo()
{
	mkdir -p $loc_blocklist
	cd $loc_blocklist
	touch remove_me
	git init
	git add .
	git commit -m "$(date +%Y%m%d_%H%M%S)_initial_commit_blocklist"
	rm remove_me

	## create branch blocklist_off
	git branch blocklist_off

	## copy original etc/hosts to branch blocklist_off
	git checkout blocklist_off
	[[ -f /etc/hosts ]] && sudo cp /etc/hosts .
	git add .
	git commit -m "$(date +%Y%m%d_%H%M%S)_created branch blocklist_off"

	## create branch blocklist_on ...
	git branch blocklist_on
	git checkout blocklist_on
	git add .
	git commit -m "$(date +%Y%m%d_%H%M%S)_created branch blocklist_on"

	## go back to where we came from
	cd -
}


download_blocklist()
{
	## ... copy THE blocklist into branch blocklist_on
	cd $loc_blocklist
	git checkout -f blocklist_on

	#[TODO] define tracking info for branch
	#[TODO] git pull
	curl -O http://sbc.io/hosts/alternates/fakenews-gambling-porn-social/hosts

	git add .
	git commit -a -m "$(date +%Y%m%d_%H%M%S)_blocklist_updated"

	## symlink /etc/hosts to blocklist
	sudo ln -sf $XDG_CONFIG_HOME/hosts/hosts /etc/hosts

	printf "${BLUE}update dns hosts blocklist succesfull${NOC}\n"

	## go back to where we came from
	cd -

	exit 0
}


[[ ! -d $loc_blocklist ]] && create_git_repo
download_blocklist
