#!/usr/bin/env sh

# voice-to-text
# with vosk
#
# usage: vtx $action [$language]

mic='Webcam C310'

action=$1

language=$2

[[ -z $action ]] && exit 11

## file locations
vosk_dir='/home/oxo/.local/share/a/data/ai/language/model/vosk-api'
vtx_app='nerd-dictation'
config_file='/home/oxo/.config/nerd-dictation/nerd-dictation.py'

## nd options
#sim_tool='STDOUT'
sim_tool='DOTOOL'
numbers='--numbers-min-value 10 --numbers-as-digits --numbers-no-suffix'

## specific language selection
case $language in

    en)
	# english
	config_file='/home/oxo/.config/nerd-dictation/specific/lang_en.py'
	using='vosk-model-small-en-us-0.15'
	model_dir="$vosk_dir/$language/$using"
	;;

    sv)
	# swedish
	config_file='/home/oxo/.config/nerd-dictation/specific/lang_sv.py'
	using='vosk-model-small-sv-rhasspy-0.15'
	model_dir="$vosk_dir/$language/$using"
	;;

    nl)
	# dutch
	config_file='/home/oxo/.config/nerd-dictation/specific/lang_nl.py'
	using='vosk-model-nl-spraakherkenning-0.6-lgraph'
	#using='vosk-model-small-nl-0.22'
	model_dir="$vosk_dir/$language/$using"
	;;

    sh)
	# shell language
	config_file='/home/oxo/.config/nerd-dictation/specific/lang_sh.py'
	using='vosk-model-small-en-us-0.15'
	model_dir="$vosk_dir/$language/$using"
	;;

    *)
	# default config
	config_file='/home/oxo/.config/nerd-dictation/nerd-dictation.py'
	using='vosk-model-small-en-us-0.15'
	model_dir="$vosk_dir/$language/$using"
	;;

esac

## bwgin and end vtx
case $action in

    begin)
	[[ -z $language ]] && exit 47

	mic_switch on "$mic"
	notify-send "$vtx_app $action"

	$vtx_app $action --simulate-input-tool $sim_tool $numbers --vosk-model-dir $model_dir
	;;

    end)
	$vtx_app $action

	notify-send "$vtx_app $action"
	mic_switch off "$mic"
	;;

esac
