#!/bin/bash

# run this script when logged in as superuser (i.e. sudo su)

user_home_dir="$HOME"

cd /root

ln -s $user_home_dir/..config/nvim/.vimrc .vimrc
ln -s $user_home_dir/.config/zsh/.zshrc .zshrc
ln -s $user_home_dir/.config/ .conifg
#mkdir -p /root/_data/journal/history/.history
#ln -s $user_home_dir/_data/journal/history/.history /root/_data/journal/history/.history

zsh
