#! /usr/bin/env sh

# cool clock with figlet fonts chosen via fzf

## choose font type
font="$(command ls "$XDG_CONFIG_HOME/figlet" | fzf)"


erase()
{
    ## delete to boginning of line
    tput el1
    ## restore cursor position
    tput rc
    ## delete line
    tput ed
}


set_stage()
{
    ## hide cursor
    tput civis
    ## save cursor position
    tput sc
}


int_handler()
{
    ## what to do on SIGINT
    tput cnorm
    callback=1
}


exit_neatly()
{
    ## how to exit on SIGINT
    trap int_handler SIGINT

    case $callback in

	1)
	    exit 0
	    ;;

    esac
}


print_loop()
{
    while :; do

	## print clock with colons
	echo
	figlet -d "$XDG_CONFIG_HOME/figlet" -f $font $(date +'%H:%M:%S')

	# possible exit point on SIGINT
	exit_neatly

	sleep 1
	erase

	## print clock with dots
	echo
	figlet -d "$XDG_CONFIG_HOME/figlet" -f $font $(date +'%H.%M.%S')

	# possible exit point on SIGINT
	exit_neatly

	sleep 1
	erase

    done
}


main()
{
    set_stage
    print_loop
}

main
