#! /usr/bin/env sh

# cool clock with figlet fonts chosen via fzf

# v0.2
# special thanks to emanresu3
# https://matrix.to/#/!esyCFwsvHGqLXuAxSC:matrix.org/$hVsUXYb7F4WaKE2Hd6Og9uaz_zB30DO3VnuNGkIOwvQ?via=grin.hu&via=matrix.org&via=envs.net

font="$(command ls "$XDG_CONFIG_HOME/figlet" | fzf)"

trap "tput cnorm; callback='return 1'" INT

erase()
{
    tput el1
    tput rc
    tput ed
}


tput civis
tput sc


while :; do

    $callback

    echo
    figlet -d "$XDG_CONFIG_HOME/figlet" -f $font $(date +'%H:%M:%S')
    sleep 1
    erase

    echo
    figlet -d "$XDG_CONFIG_HOME/figlet" -f $font $(date +'%H.%M.%S')
    sleep 1
    erase

done
