#! /usr/bin/env sh

#audio_sources=$(pactl list sources | grep -e device.description -e node.name)
#
#for line in $audio_sources; do
#
#    :
#
#done

get_node_name()
{
    # get node.name from device.description
    source_list=$(pactl list sources | grep -e 'device.description' -e 'node.name')
    sel_descr=$(printf "$source_list" | grep 'device.description' | awk -F '"' '{print $2}' | sort | uniq | fzf)
    sel_node=$(printf "$source_list" | grep -A 1 "$sel_descr" | grep node.name | awk -F '"' '{print $2}')
}


get_action()
{
    sel_action=$(printf 'off\non' | fzf)
}


activate_mic()
{
    pactl suspend-source $sel_node false
    pactl set-source-port $sel_node analog-input-mic
    pactl set-source-volume $sel_node 100%
    pactl set-source-mute $sel_node false
}


deactivate_mic()
{
    pactl set-source-port $sel_node analog-input-mic
    pactl set-source-volume $sel_node 0%
    pactl set-source-mute $sel_node true
    pactl suspend-source $sel_node true
}


execute()
{
    case $sel_action in

	off)
	    deactivate_mic
	    ;;

	on)
	    activate_mic
	    ;;

    esac
}


main()
{
    get_action
    get_node_name
    execute
}

main
