#! /usr/bin/env sh

set -o errexit
set -o nounset
set -o pipefail

## process_data
pd=$(ps -eFly)

## sensor_data
sd=$(sensors -u 2> /dev/null)

## nano_second
ns=$(date +'%N')

## random_ascii
ra=$(ascii=$(for (( i=32; i<127; i++ )) do printf "\\$(printf %03o "$i")"; done))

## 32 bytes random interpret as unsigned decimal
od=$(od --output-duplicates --address-radix=n --read-bytes 32 --format u < /dev/urandom | tr -d ' ')

## 32 bytes random interpret ascii
od=$(od --output-duplicates --address-radix=n --read-bytes 32 --format a < /dev/urandom | tr -d ' ')

## history tail
ht=$(tail -n10 $HISTFILE)

## two concatenated srandom numbers from bash
sr=$(bash -c 'echo $SRANDOM$SRANDOM')

## synthesized hash and extract numbers
printf '%s%s%s%s%s%s%s%s%s\n' $pd $sd $ns $ra $od $ht $sr
